id = "gitlab-ci-ls"
name = "gitlab-ci-ls"
version = "1.0.0"
schema_version = 1
authors = ["Tom Zaspel tom@zaspel.it"]
description = "Language Server for gitlab-ci"
repository = "https://github.com/tzabbi/zed-gitlab-ci-ls"
